// accounts
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_USER_INFO = 'SET_USER_INFO'
export const DESTROY_ACCESS_TOKEN = 'DESTROY_ACCESS_TOKEN'
export const DESTROY_CURRENT_USER = 'DESTROY_CURRENT_USER'
