// project
export const FETCH_PROJECT_LIST = 'FETCH_PROJECT_LIST'
export const FETCH_PROJECT = 'FETCH_PROJECT'
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST'
export const FETCH_FLOOR_TYPE_LIST = 'FETCH_FLOOR_TYPE_LIST'
export const FETCH_BUILDING_LIST = 'FETCH_BUILDING_LIST'
export const FETCH_HOUSE_UNIT_LIST = 'FETCH_HOUSE_UNIT_LIST'
export const FETCH_NUM_UNIT_BY_TYPE = 'FETCH_NUM_UNIT_BY_TYPE'
