// project
export const FETCH_PROJECT_LIST = 'FETCH_PROJECT_LIST'
export const FETCH_PROJECT = 'FETCH_PROJECT'
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST'
export const FETCH_FLOOR_TYPE_LIST = 'FETCH_FLOOR_TYPE_LIST'
