// proCash
export const FETCH_P_ACC_SORT_LIST = 'FETCH_P_ACC_SORT_LIST'
export const FETCH_ACCOUNT_D1_LIST = 'FETCH_ACCOUNT_D1_LIST'
export const FETCH_ACCOUNT_D2_LIST = 'FETCH_ACCOUNT_D2_LIST'
export const FETCH_P_BANK_ACCOUNT_LIST = 'FETCH_P_BANK_ACCOUNT_LIST'
export const FETCH_P_CASHBOOK_LIST = 'FETCH_P_CASHBOOK_LIST'
