// coCash
export const FETCH_ACC_SORT_LIST = 'FETCH_ACC_SORT_LIST'
export const FETCH_COM_ACC_D1_LIST = 'FETCH_COM_ACC_D1_LIST'
export const FETCH_COM_ACC_D2_LIST = 'FETCH_COM_ACC_D2_LIST'
export const FETCH_COM_ACC_D3_LIST = 'FETCH_COM_ACC_D3_LIST'
export const FETCH_COMPAY_BANK_LIST = 'FETCH_COMPAY_BANK_LIST'
export const FETCH_CASHBOOK_LIST = 'FETCH_CASHBOOK_LIST'
