/* contract */
export const FETCH_CONTRACT_LIST = 'FETCH_CONTRACT_LIST'
export const FETCH_CONTRACT = 'FETCH_CONTRACT'
export const FETCH_ORDER_GROUP_LIST = 'FETCH_ORDER_GROUP_LIST'
export const FETCH_SUBS_SUMMARY_LIST = 'FETCH_SUBS_SUMMARY_LIST'
export const FETCH_CONT_SUMMARY_LIST = 'FETCH_CONT_SUMMARY_LIST'
